<!DOCTYPE html>
<html>

<head>
    <title>Laporan Parkir</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
            line-height: 1.6;
        }

        h2 {
            text-align: center;
            margin-bottom: 5px;
        }

        p.subtitle {
            text-align: center;
            font-size: 14px;
            margin-bottom: 20px;
            color: #777;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th,
        td {
            border: 1px solid #ddd;
            text-align: center;
            padding: 10px;
            font-size: 12px;
        }

        th {
            background-color: #004085;
            color: #fff;
            text-transform: uppercase;
            font-size: 13px;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tbody tr:hover {
            background-color: #e9ecef;
        }

        .footer {
            text-align: right;
            font-size: 12px;
            color: #555;
            margin-top: 10px;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }

        .header-line {
            width: 100%;
            height: 2px;
            background-color: #004085;
            margin-bottom: 10px;
        }

        .footer-line {
            width: 100%;
            height: 2px;
            background-color: #004085;
            margin-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header-line"></div>
    <h2>Laporan Parkir</h2>
    <p class="subtitle">Sistem Parkir Otomatis Terjamin (SPOT)</p>
    <table>
        <thead>
            <tr>
                <th>ID Parkir</th>
                <th>Nama Pengguna</th>
                <th>Plat Nomor</th>
                <th>Waktu Masuk</th>
                <th>Waktu Keluar</th>
                <th>Lama Parkir</th>

            </tr>
        </thead>
        <tbody>
            @foreach ($riwayatParkir as $parkir)
            <tr>
                <td>{{ $parkir->id_riwayat_parkir }}</td>
                <td>{{ $parkir->pengguna->nama }}</td>
                <td>{{ $parkir->plat_nomor }}</td>
                <td>{{ $parkir->waktu_masuk }}</td>
                <td>{{ $parkir->waktu_keluar }}</td>
                <td>{{ $parkir->lama_parkir}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer-line"></div>
    <div class="footer">
        <p>Generated by SPOT - {{ now()->format('d/m/Y H:i:s') }}</p>
    </div>
</body>

</html>